# Examen


::: {.callout-important}
## Vous avez le choix entre deux sujets
Choisissez le sujet que vous voulez, entre le premier ou le deuxième sujet !
:::

## Premier sujet

Le [premier sujet](https://www.recrutement.banque-france.fr/app/uploads/2023/09/CCS_CDIR_2023_ECSE.pdf) est une étude de cas de stratégie d’entreprise qu’on retrouve au concours de la Banque de France.

## Deuxième sujet

Le deuxième sujet est relatif au cours, vous devez mettre en application les éléments abordés ensemble.

### Questions (5 points) :

1. Quelle est la différence fondamentale entre la cotation et la notation ? Pouvez-vous me citer une agence de notation ?
2. Que signifie une cotation « à dire d’expert » ? Quelle est la différence avec le scoring ?
3. Citez la « philosophie » d’analyse qui permet de justifier tous les retraiments de la Banque de France.
4. Qu’est-ce qu’une SCI : quelle est l’objectif d’une SCI et pourquoi doit-on y prêter une attention particulière ?
5. Comment définissez-vous le résultat net récurrent (RNR) ?

### Approfondissement du sujet (3 points) :

Les questions suivantes n’ont pas été abordé pendant le cours. Vous devez faire vos propres recherches et rédiger vos réponses en fonction des notions vues ensemble :

1. Qu’est-ce qu’un SPAC ?
2. Énumérer les différentes formes d’analyse financière et les comparer à celle étudier pendant les 2 jours.

### Étude de cas (12 points) :

Analysez de façon critique et pensez à bien argumenter chacune de vos réponses.

1. Compte tenu des informations suivantes, peut-on raisonner en endettement financier net ou brut ?

> L’organisation financière s’articule autour d’un cash pooling auprès de la Banque Populaire qui couvre l’ensemble des sociétés françaises ; il n'existe pas de frein à la circulation des flux.L’endettement financier est porté principalement par les différentes filiales portant des programmes d’investissements photovoltaïques. Le financement de ces projets est réalisé par fonds propres pour 15% et par dette bancaire pour 85% via des prêts bancaires avec une maturité de 19 ans. Il existe très peu de financement "corporate".

2. Réaliser la matrice SWOT en vous basant sur le compte-rendu d’entretien suivant.

::: {.callout-note}
Le groupe est un prestataire de services spécialisé dans la maintenance des systèmes électriques et électroniques. La vocation du groupe est donc de maintenir en condition opérationnelle les systèmes d’entrainement électroniques et électriques utilisés par ses clients industriels, ferroviaires et automobiles.

Sur son principal marché le concurrent du groupe est XYZ. La différenciation entre ces deux acteurs est la qualité. Le groupe est positionné sur une qualité "premium" avec un taux de réussite sur les réparations de 99% tandis que son concurrent XYZ possède un taux de réussite de ses réparations de 80%.La segmentation prix est donc différente, le prestation du groupe est plus onéreuse.

Le groupe est implanté en France avec 11 sites spécialisés dans les servomoteurs, l'électronique et l'électrique ; en Allemagne , grâce à la croissance externe, depuis 2015 ; et finalement, en Chine où le groupe essaie de percer le marché chinois depuis plusieurs années.

En tant que réparateur indépendant, le groupe dispose de partenariats avec les plus grands fournisseurs d'appareils électriques, électroniques et servomoteurs afin d'être identifié par les clients comme un réparateur agréé de la marque. Ainsi, le groupe possède des partenariats avec Siemens (part de marché mondiale estimée à 40%), Fanuc (industriel japonais disposant d'une part de marché estimée de 20%) et Bosch (10% de part de marché estimée). Compte tenu de la prédominance d'acteurs allemands, il était donc important pour le groupe de s'implanter physiquement en Allemagne afin d'asseoir sa position de leader européen.

La stratégie du groupe repose sur deux axes de développement. Le premier est le renforcement de la position de leader sur les technologies à forte valeur ajoutée grâce à une constante innovation sur l’électronique et les servomoteurs. En effet, les dépenses de recherche & développement représentent chaque année 3% à 4% du chiffre d'affaires consolidé.

Le second axe de développement est l’international, avec des acquisitions en Europe et des créations d’entités en Asie. L’objectif du groupe est d’atteindre une taille critique (50 M€ de chiffre d’affaires et 400 collaborateurs) afin de devenir un acteur européen incontournable.

Afin que le groupe puisse se développer, la condition de marché "optimale" est une croissance du PIB comprise entre 1% et 2,5%. Dans cette fourchette, l'investissement industriel est partiel et les entreprises font plus appel à la maintenance qu'au renouvellement des immobilisations. Dans ces conditions, le ralentissement de la croissance en Chine apparaît comme opportun pour pénétrer le marché et s'imposer comme un acteur de référence dans un pays où le parc de robots et de circuits électroniques est le plus important du monde. Il représente un marché de 200 M€.

### Chine :

Le chiffre d'affaires est inférieur au budget prévisionnel en 2016, 2017 et 2018 à cause des difficultés pour pénétrer ce marché. Les projections actualisés de marge EBE sont de -500 K€ en 2016 et -700 K€ en 2017. La croissance en Chine reste un foyer de coût pour le groupe. Le point d'équilibre devrait être atteint au début de l'année 2020, voir 2021. Pour le moment, ce relais de croissance est amorti par les marges réalisées en Europe.

### Stratégie :

Dans la recherche de marché à forte valeur ajoutée, le groupe cherche des relais de croissance dans l'industrie aéronautique et militaire avec pour commencer les bornes de test des rafales et les tourelles des chars français. Ce nouveau segment nécessite une certification GR23 que le groupe est en train d'obtenir. Avec ce débouché, le groupe espère conforter ses marges
:::

3. En vous basant sur les comptes consolidés, [disponible ici](https://numberly.com/2023/04/1000mercis-document-d-informations-31-decembre-2022.pdf), calculez :
    1. Le résultat net récurrent ;
    2. Les fonds propres nets réduits ;
    3. Le taux d’endettement

