---
title: "Exercices d'Analyse Finnancère"
---

## Exercice 1 : analyse de l'environnement

L’exploitation de carrières (granulats) représente 90 % du chiffre d’affaires. Le groupe dispose d’une cinquantaine de sites à l’ouest d’une ligne Rouen-Montpellier. Le reste de l’activité est consacrée à la production de bétons et de travaux publics, activité consommatrice de granulats.

L’exploitation d’une carrière nécessite une autorisation préfectorale (de plus en plus longue à obtenir) demandant 2 à 3 ans de formalités (commission de carrières statuant sur la continuité d’exploitation ou la création). Les normes environnementales sont plus fortes, un réaménagement du site en fin de vie est obligatoire et les nuisances (bruits, poussières, flux de camions) sont de moins en moins acceptées de la population avoisinante. L’autorisation d’exploitation est temporaire : durée de 20 à 30 ans, ou de 10 à 15 ans, mais qui peut être renouvelée.

Le groupe estime avoir des réserves importantes de gisements (entre 25 et 35 années) sur des sites diversifiés. Les achats de gisements sont des opérations d’opportunité, par connaissance. Généralement, les acquisitions de terrains sont réalisées auprès de particuliers (agriculteurs), soit pour étendre des gisements existants ou pour en créer de nouveaux, soit par rachat de gisements en cours d’exploitation, plus chers à l’achat, mais qui ont l’avantage de bénéficier déjà de l’autorisation préfectorale, mais il y a de moins en moins d’opportunités. La taille modeste du groupe et ses relations de proximité lui permettent cependant de trouver de bons sites et d’être très réactif en cas de baisse d’activité (effectif à forte composante d’intérim, organisation resserrée).

L’activité nécessite des matériels lourds à renouvellement rapide (forte abrasion) et très énergivore (fuel, électricité), dans un contexte de tension sur les prix des matières premières et d’expérience peu réussie avec un opérateur alternatif.
En ce qui concerne l’activité de travaux publics, les dirigeants ont été remerciés pour mauvaise gestion (prise de chantiers non rentables) et l’activité est en perte depuis 2 ans. Suite à la restructuration, l’avenir de cette activité n’est pas décidé, une cession étant possible après la restructuration.

Le marché est partagé entre les routiers (VINCI, COLAS, EIFFAGE, EUROVIA), les cimentiers (LAFARGE, HOLCIM) et les indépendants dont le groupe, qui a produit 15 millions de tonnes de granulats cette année, est leader. L’activité du groupe s’appuie sur le marché du BTP en France alors que ses grands concurrents profitent des marchés internationaux.

Le portefeuille clients est diffus avec 60 % d’entreprises de terrassement et de sociétés de travaux publics, le solde correspondant à ses concurrents et à la SNCF (ballast). Le marché est essentiellement local (rayonnement de 60 km) car la part du coût du transport dans le prix est très importante (de l’ordre de 50-60 %). Hormis les chantiers importants, source de gros volume et de pic d’activité, qui représentent moins de 10 % du chiffre d’affaires, le groupe n’a pas de carnet de commandes et les ventes se font au fil de l’eau.
Travail à faire

### Travail à faire :

> Déterminer, en complétant le tableau ci-dessous, les éléments de l’environnement du groupe qui constituent une menace ou une opportunité et les avantages et les faiblesses du groupe vis-à-vis de ses concurrents.

## Exercice 2 : analyse des performaces

Le groupe installe et loue des systèmes télévisuels à destination principalement du secteur hôtelier.

| RUBRIQUES                                           | Montants (en k€) |
| --------------------------------------------------- | :--------------: |
| Chiffre d’affaires                                  |      50 807      |
| Achats consommés, autres achats et charges externes |      21 739      |
| Charges de personnel                                |      15 083      |
| Impôts et taxes                                     |       699        |
| Dotations nettes aux amortissements                 |      3 922       |
| Dotations nettes aux provisions                     |       583        |
| Autres charges et produits d’exploitation           |       567        |
| Résultat d’exploitation                             |      8 214       |
| Produits financiers                                 |        64        |
| Charges financières                                 |      3 750       |
| Résultat financier                                  |     (3 686)      |
| Résultat courant avant impôt                        |      4 528       |
| Produits exceptionnels                              |      1 500       |
| Charges exceptionnelles                             |      2 227       |
| Résultat exceptionnel                               |      (727)       |
| Charge d’impôt                                      |      1 802       |
| Dotation aux amortissements sur écart d’acquisition |      1 227       |
| Résultat net consolidé                              |       772        |

L’analyse du dossier met en évidence les points suivants :

1.	Les charges de personnel comprennent le coût de restructuration suite à l’arrêt total des activités en Belgique pour `1,8` M€.
2.	Un litige important avec un ancien dirigeant a été provisionné pour 500 K€ dans le résultat d’exploitation.
3.	Les charges financières comprennent les frais relatifs au refinancement pour `1,3` M€ d’un emprunt.
4.	Les produits exceptionnels comprennent le résultat de cession du matériel de location pour `1` M€.

### Travail à faire

> Déterminer la performance de ce compte de résultat simplifié

## Exercie 3 : analyse des fonds propres

Le groupe est positionné dans la production et la commercialisation de produits laitiers ultra frais. Disposant d’une large gamme de produits et présent dans de nombreux pays grâce à son système de franchise, il est un des leaders européens du marché et il bénéficie d’une forte notoriété. Il dégage des marges régulières mais il est exposé aux variations des cours du lait et des monnaies hors euro.

| Extrait des comptes (montants en k€)   |   N-2   |   N-1   |    N    |
| -------------------------------------- | :-----: | :-----: | :-----: |
| Immobilisations incorporelles          | 284 950 | 344 983 | 350 076 |
| _dont fonds de commerce_               | 20 000  | 20 000  | 20 000  |
| _dont marques_                         | 148 999 | 148 999 | 148 999 |
| _dont parts de marché_                 | 105 000 | 160 000 | 160 000 |
| Écarts d’acquisition                   | 228 022 | 290 531 | 285 898 |
| Impôts différés actif                  | 34 288  | 52 682  | 63 326  |
| Capitaux propres totaux                | 390 593 | 498 756 | 562 955 |
| _dont écarts de conversion_            | (1 843) |  3 948  | 47 335  |
| Provisions pour impôts différés passif |    0    |    0    |    0    |
| Résultat courant avant impôt           | 56 909  | 75 582  | 89 764  |
| Charge d’impôt                         | 15 943  | 18 347  | 25 741  |

#### Détail des impôts différés actif

| Extrait des comptes (montants en k€)      |  N-2   |  N-1   |     N     |
| ----------------------------------------- | :----: | :----: | :-------: |
| Impôts différés actif                     | 34 288 | 52 682 |  63 326   |
| dont décalage temporel                    | 6 510  | 14 824 |   9 174   |
| _dont relatif à des déficits reportables_ | 27 500 | 37 025 | 52 045(1) |

(1) : dont 27 M€ sur une filiale étrangère en difficulté (des pertes sont attendues sur les deux prochains exercices) et 25 M€ sur les filiales françaises

#### Détail des écarts de conversion

| Extrait des comptes (montants en k€)     |   N-2   |  N-1  |   N    |
| ---------------------------------------- | :-----: | :---: | :----: |
| Écarts de conversion                     | (1 843) | 3 948 | 47 335 |
| _dont issus d’opérations hors zone euro_ |  (900)  | 2 509 | 44 520 |

### Travail à faire

Analyser les fonds propres.

## Exercice 4 : analyse de l'endettement financier

1. L’analyse de l’organisation financière du groupe met en évidence :
   - une trésorerie centralisée au niveau de la holding ;
   - une forte concentration de la trésorerie et de l’endettement sur un nombre restreint de filiales opérationnelles ;
   - des intérêts minoritaires non significatifs.
   - Le groupe a placé 5 M€ dans une banque chinoise dans la perspective d’un développement industriel dans cette zone.
2. L’analyse du poste « Autres dettes » révèle la présence d’un crédit-vendeur pour l’acquisition d’une société industrielle qui s’élève à 12 M€.
3. Les engagements hors bilan comprennent une caution de 10 M€ sur une société partenaire détenue par le groupe à 35 % et mise en équivalence. Cette société traverse une passe très difficile et un redressement judiciaire apparaît probable dans un avenir proche.
4. L’immeuble du siège social est porté par une société détenue directement par les associés du groupe mais non consolidée dans le groupe. L’analyse des déclarations de risques de cette société met en avant la présence d’engagements bancaires pour un encours moyen de 9 M€.
5. Des mobilisations de créances d’un montant total de 12 M€ ont été détectées lors du rapprochement avec les risques. Le groupe confirme un montant de mobilisations supérieur à celui présenté dans le bilan.

| Extrait des comptes (montants en k€)                 |   N    |
| ---------------------------------------------------- | :----: |
| Valeurs mobilières de placement                      | 15 334 |
| Disponibilités                                       | 44 413 |
| Dettes financières                                   | 59 010 |
| _dont emprunts auprès des établissements de crédit_  | 52 527 |
| _dont concours bancaires et soldes créditeurs_       | 6 979  |
| _dont crédit-bail_                                   | 6 103  |
| Autres dettes                                        | 50 447 |
| Effets escomptés non échus et autres créances cédées | 7 677  |

### travail à faire

Analyser l'endettement, quel montant d'endettement financier retenez-vous ?
