---
title: Guide la cotation Banque de France
--- 

## Guide de Référence - Mise à jour en janvier 2022

---

## Sommaire

1. La cotation : un processus d’appréciation de la situation financière des entreprises
    - 1.1 Pourquoi la Banque de France cote-t-elle les entreprises ?
    - 1.2 Quelles sont les entreprises cotées ?
    - 1.3 Quels sont les destinataires de la cotation ?
    - 1.4 Quels sont les types d’informations collectées ?
    - 1.5 Comment la Banque de France attribue-t-elle une cotation ?

2. La cotation : une appréciation synthétique
    - 2.1 Un exemple de cotation
    - 2.2 La cote d’activité exprime un niveau d’activité
    - 2.3 La cote de crédit apprécie la capacité de l’entreprise à honorer ses engagements financiers à un horizon de trois ans

3. Annexe : cadre juridique

---

## 1. La cotation : un processus d’appréciation de la situation financière des entreprises

### 1.1 Pourquoi la Banque de France cote-t-elle les entreprises ?

La cotation de la Banque de France est une appréciation sur la capacité d’une entreprise domiciliée en France à honorer ses engagements financiers à un horizon d’un an à trois ans.

Elle est utilisée pour :
- les besoins de la politique monétaire ;
- l’analyse des risques sur les entreprises, comme appui aux établissements de crédit ;
- le calcul des besoins en fonds propres des établissements de crédit.

Grâce à la cotation, la Banque de France :
- fournit aux prêteurs une information sur la qualité des engagements ;
- aide les chefs d’entreprise à identifier les facteurs qui influent sur leur situation financière ;
- facilite le dialogue prêteur-entreprise.

### 1.2 Quelles sont les entreprises cotées ?

Les entreprises cotées sont celles dont le siège social se trouve en France, à partir des informations contenues dans la base de données Fiben (Fichier bancaire des entreprises).

Certaines entités ne reço
