---
title: Introduction to Credit Risk Analysis
---

## Avant-propos

Ce livre est destiné aux élèves de MSc2 en **Manager Financier, Banque &
Assurance** et **Banque d’Affaires & Ingénierie Financière**.

<!-- [ ] Add more description -->

## Plan du cours

### Banque de France

1. Stratégie Monétaire
2. Stabilité Financière
3. Service à l’économie

- Définition et objectifs de la cotation BdF
- Liens avec la stabilité financière
- Comment est-elle gérer par les banque privées.

### Analyse des comptes consolidés

### Les flux de trésorerie

1. Découvrir la Banque de France et la cotation
2. Introduction aux comptes consolidés et à leurs analyses financièrs
3. Analyse du compte de résultat
4. Analyse du bilan
5. Analyse du tableau des flux de trésorerie
6. Examen final sur un cas pratique

<!-- [ ] Add link to `.qmd` files -->



## Cotation

La cotation de la Banque de France est une appréciation sur la capacité d’une entreprise à honorer ses engagements financiers (remboursement des dettes et souscription de nouveaux financements) à un horizon d’un an à trois ans.

COTATION A DIRE D’EXPERT
Attribuée par des analystes financiers de la Banque de France aux entreprises dont le chiffre d’affaires annuel est supérieur à 750 000 €
analyse de la documentation comptable
et d’informations extracomptables qualitatives et prévisionnelles recueillies auprès des dirigeants lors d’entretiens
La cotation à dire d’expert concerne l’ensemble des positions de l’échelle de risque de crédit.

COTATION SANS COLLECTE DE BILAN
Réservée aux entreprises dont le chiffre d’annuel ne dépasse pas 750 000 € et dont la documentation comptable n’est pas étudiée
informations recueillies auprès des greffes des Tribunaux de Commerce, de l’Insee et de la Centrale des Incidents de Paiement sur Effets dont la Banque de France assure également la gestion.
la cote de crédit 0 est attribuée lorsqu’aucune information défavorable n’est relevée.


- https://www.banque-france.fr/fr/a-votre-service/entreprises/comprendre-cotation-indicateur-dirigeant
- [Qu’est-ce que la cotation Banque de France ?](https://www.youtube.com/watch?v=rDu2IJKCl_w)

### Une évaluation du risque de crédit

- Objet : une appréciation portée sur la capacité d’une entreprise domiciliée en France à honorer ses engagements financiers à un horizon de un à  trois ans. 
- Double labellisation :
    - La Banque de France est reconnue organisme externe d’évaluation du crédit  (OEEC) ce qui atteste du respect des critères internationaux d’évaluation du risque de crédit : Objectivité, Indépendance, Transparence et publicité de la méthode, Large utilisation par la profession bancaire, Critères de performances normés et vérifiés.
    - En Europe, la Banque de France est l’une des banques centrales disposant d’un système propre d’évaluation du risque de crédit ayant obtenu le statut d’ICAS (In house Credit Assessment System).

> Un même objet, mesurer le risque de défaut, mais des caractéristiques propres qui diffèrent sensiblement des autres agences de notation 

### Qui accède à la cotation

Les banques
2013 : Les assureurs crédit
2014 : Les plateformes de crowd funding 
2016 : Entreprises d’assurance, Mutuelles, Institutions de prévoyance, Certaines  Sociétés de Gestion de Portefeuille…
2018 : Conseil régional pour leur action d’aides aux entreprises (Pour une partie seulement de la base de données FIBEN) 
2020 : Administrations intervenants dans la prévention des difficultés des entreprises.
Depuis 2018, les Conseils Régionaux peuvent bénéficier des services suivants :
27 «panorama de l’entreprise », 
37  « cotation et son explication », 
39 « segmentation » 
68 « dossier comptable et financier »
 
Depuis le 1er janvier 2021, nous avons ouvert la consultation du module 28 « sources de financement », donc pas d’accès aux liens financiers, dirigeants 

### Une performance évaluée par le taux de défaut ICAS

1+ / 1- =  0,1%
2+ / 2- = 0,4%
3+ / 4+ = 1%
4 = 1,5%
4- / 5+ = 3%
5 / 5- = 5%
6+ / 8 = 100

### répartition des cotes

image1.png

### Capacité prédictive du modèle et conformité aux exigences OEEC (stat 2020)

La Banque de France fait partie de la liste des Organismes Externes d'Évaluation de Crédit (OEEC). Cela
permet aux établissements de crédit d'utiliser la cotation Banque de France pour évaluer leur besoin en
fonds propres nécessaires à la couverture du risque de crédit.
Le statut d’OECC conduit en effet la Banque de France à respecter des seuils de taux de défaut sur toute
l’échelle de cotation à l’horizon de 3 ans (Tableau 1).
L’analyse des données indique une progressivité satisfaisante des taux de défaut et de défaillance sur
toute l’étendue des cotes de crédit et sur les trois horizons temporels étudiés.
Globalement, le taux de défaut des entreprises cotées s’établit à 0,63% à l’horizon d’un an, à 1,65% à deux
ans et à 2,59% à l’horizon de trois ans. (Tableau 1 et Annexe 2)
Le taux de défauts BDF à 3 ans respecte les seuils définis par l’OEEC.

### Définition de la défaillance et du défaut

La Banque de France utilise deux notions correspondant à des conceptions plus ou moins extensives du défaut :

une entreprise est dite défaillante en cas d’ouverture d’une procédure judiciaire (redressement ou liquidation) à son encontre : l’entreprise reçoit alors une cote P. Même lorsque cette cote est ensuite remplacée par une cote plus favorable, suite à l’adoption d’un plan de continuation par exemple, l’entreprise reste dans la catégorie de la défaillance pour le calcul des statistiques ;

une entreprise est dite en défaut si elle satisfait à la condition précédente (procédure judiciaire) ou si elle reçoit une cote 9 au cours de la période d’observation en raison d’incidents de paiement sur effet de commerce (IPE) importants déclarés par un ou plusieurs établissements de crédit. Cette définition ne correspond pas à celle du « défaut bâlois », collecté depuis 2012. La période considérée pour l’attribution de cette cote est celle des 6 derniers mois. Ainsi, après l’attribution d’une cote 9, si une société voit ses paiements redevenir réguliers, elle peut sortir de la catégorie en défaut et se voir attribuer une cote plus favorable, après une étude globale de sa situation par un analyste. Toutefois, là encore, le dossier reste dans la catégorie du défaut pour le calcul des statistiques.

Par construction, le taux de défaut calculé pour une population donnée est toujours supérieur ou égal au taux de défaillance et le taux de défaut des entreprises initialement cotées 9 est de 100 %.

La notion de défaillance, qui constitue une approche objective du risque est disponible de façon exhaustive et quasiment instantanée dès que la déclaration en est faite.
La notion de défaut, plus extensive, s’appuie sur les données de la base de centralisation des incidents de paiement sur effets de commerce (fichier Central des Incidents de Paiement sur Effets – CIPE) gérée par la Banque de France en vertu du règlement du comité de la réglementation bancaire n° 86-08 en date du 27 février 1986. La CIPE réceptionne et centralise les déclarations d’incidents7 effectuées par les établissements de crédit. Leur gravité influence le niveau de la cote qui peut prendre, selon cette gravité, les valeurs 78 (apparition d’incidents pour incapacité de payer de faible ampleur au cours des 6 derniers mois), 8 (d’après les incidents déclarés sur les 6 derniers mois, la solvabilité de l’entreprise apparaît menacée), ou 9 (d’après les incidents de paiement déclarés sur les 6 derniers mois, la solvabilité de l’entreprise est gravement compromise).

En comparaison de la défaillance, le défaut appréhendé à travers les incidents de paiement de l’entreprise correspond donc à une mesure plus précoce et plus extensive du défaut. En effet la sinistralité élevée des entreprises cotées 9, qui ont enregistré d’importants incidents de paiement et reviennent peu souvent à meilleure fortune, justifie d’assimiler cette dernière cote de crédit à une catégorie de défaut. Elle se distingue toutefois de la notion de défaut au sens du Règlement du Parlement et du Conseil européen n° 575/2013, article 178, concernant les exigences prudentielles applicables aux établissements de crédit (CRR)9.
Dans le cas présent, il s’agit d’un défaut limité aux effets de commerce, non mesuré sur la totalité de la dette, mais l’importance du crédit interentreprises dans le financement des entreprises rend la prise en compte de ces incidents de paiement particulièrement appropriée pour l’analyse du risque crédit.
Cette notion de défaut présente également de grandes qualités en regard des impératifs de prédictivité et de stabilité :
 indicateur suffisamment prédictif car, souvent, le défaut sur effets de commerce précède le défaut sur prêt bancaire, qui lui-même précède le défaut sur obligation et le défaut « légal » constitué par l’ouverture d’une procédure collective (car ces deux derniers mettent au grand jour les difficultés d’une société),
 indicateur suffisamment « stable » pour être opérationnel, c’est-à-dire n’étant pas associé à un taux trop important ou trop rapide de retour dans des catégories « saines ».
