---
title: Syllabus du cours Analyse financière et diagnostic
---

## ANALYSE FINANCIÈRE ET DIAGNOSTIC

1. Réaliser une analyse financière d’entreprises en normes françaises (liasse fiscale) ou internationales (IFRS et US GAAP) en fonction du point de vue choisi (investisseur ou créancier).
2. Utiliser les outils de collecte et d’analyse de l’information financière (Bloomberg...).
3. Porter un diagnostic sur la profitabilité, la rentabilité, la politique d’investissement et de financement de l’entreprise.
4. Découvrir les différences entre les normes comptables françaises, les normes comptables internationales (IFRS) et les normes anglo-saxonnes (US GAAP).

## Résumé du cours : objectifs pédagogiques et professionnels

> Utiliser les outils de collecte et d’analyse de l’information financière.
> Porter un diagnostic sur la profitabilité, la rentabilité, la politique d’investissement et de financement de l’entreprise.  
> Réaliser une analyse financière d’entreprises en normes françaises (liasse fiscale) ou internationales (IFRS et US GAAP) en fonction du point de vue choisi (investisseur ou créancier).

## Connaissances et compétences RNCP visées

- 4.14 Optimiser la communication financière de l’entreprise en utilisant les leviers comptables et fiscaux à sa disposition ;
- 4.15 Utiliser les canaux d’informations financières publics à disposition en maîtrisant le rating et les actualités marché ;
- 4.16 Appliquer les normes comptables et financières internationales (USGAP, IFRS) afin d’accompagner l’entreprise dans sa gestion et le déploiement de sa stratégie à l’international.

## Plan de cours

| Date             | Contenu de la séance                                                        | Type de cours                         | Travail préparatoire                                                                                                                                         |
| ---------------- | --------------------------------------------------------------------------- | ------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| 1re demi-journée | découvrir la Banque de France et sa cotation                                | cours magistral                       | Lecture: [Guide référence](https://www.banque-france.fr/fr/system/files/2023-08/Banque%20de%20France%20%E2%80%93%20Entreprises_guide-fiben-ref-cotation.pdf) |
| 2e demi-journée  | introduction sur les comptes consolidés et l'analyse financière             | cours magistral                       |                                                                                                                                                              |
| 3e demi-journée  | analyse du compte de résultat + CC sur les demi-journées 1 et 2             | cours magistral et exercice en groupe |                                                                                                                                                              |
| 4e demi-journée  | analyse du bilan                                                            | cours magistral et exercice en groupe |                                                                                                                                                              |
| 5e demi-journée  | analyse du tableau des flux de trésorerie + CC sur les demi-journées 3 et 4 | cours magistral et exercice en groupe |                                                                                                                                                              |
| 6e demi-journée  | examen final sur un cas pratique                                            | examen individuel                     |                                                                                                                                                              |

## Bibliographie indicative

- [Vernimmen](https://www.vernimmen.net/Vernimmen/Qu_est_ce_que_le_vernimmen.php)
- [La Lettre Vernimmen.net](https://www.vernimmen.net/Lire/Lettre_Vernimmen.php) (_newsletter mensuelle_)

## Évaluation du module

1. CC - QCM : 30 % de la note finale ;
2. Examen final - cas pratique : 70 % de la note finale.
