---
title: Structure financière
format: 
  html: 
    toc: true
    toc-depth: 3
---

## Objectifs de cette étape

Déterminer le degré de solvabilité du groupe :

1. Valeur effective des fonds propres (risque potentiel de survalorisation en cas d’existence éventuelle de non-valeurs).
2. Niveau effectif de l’endettement financier (classement de certains éléments du passif tels que les titres hybrides 	et les comptes courants d’associés, traitement des 	engagements et des risques hors bilan, choix de l’agrégat d’endettement retenu).

Déterminer le degré d’autonomie financière : capacité d’autofinancement récurrente et capacité de remboursement

## Fonds propres

Les fonds propres (FP) sont une résultante : Actifs – Dettes. Ils dépendent de la valorisation des postes :

- « classiques » : immobilisations, stocks, autres créances…
- « spécifiques à la consolidation » : écarts d’acquisition, impôts différés, intérêts minoritaires, provisions pour départs en retraite, écarts de conversion.

> Indicateur d’alerte : fonds propres nets réduits (FPNR)
> FPNR = FP – écart d’acquisition élargi – impôts différés actif – écarts de conversion positifs

## Évaluation des Écarts d’Acquisition

Lorsque l’écart d’acquisition élargi est significatif ou que le montant des fonds propres nets réduits est sensiblement inférieur à celui des fonds propres publiés par le groupe, il est nécessaire de circonscrire la valeur de l’écart d’acquisition élargi aux profits générés par l’investissement sur 10 ans. L’excédent est assimilé à une non-valeur.

Le délai du retour sur investissement doit être affiné en fonction du secteur d’activité et lorsque la visibilité sur les rendements attendus est faible (la durée de 10 ans peut paraître excessive) ou forte (la durée de 10 ans peut paraître réduite). Par défaut, la rentabilité d’une filiale est estimée à 10 fois son résultat net récurrent.

Lorsqu’on ne dispose pas du détail de l’écart d’acquisition par filiale, ni des performances des filiales concernées, l’écart d’acquisition global peut être comparé au résultat net récurrent du groupe.

## Les impôts différés

Il s’agit de la différence entre l’impôt économiquement justifié et l’impôt exigible. Les impôts différés proviennent :

- des décalages entre la constatation comptable des produits et des charges et leur inclusion dans le résultat fiscal.
- de l’impact fiscal théorique des retraitements de 	consolidation (déficits fiscaux reportables).
- de la fiscalité latente liée à la revalorisation du bilan dans le cadre d’une acquisition d’entreprise.

### Impôts différés actifs

Une société provisionne, cette année, $120$ k€ d’engagements de retaite.

1. **Dans les comptes sociaux**

  - Enregistrement d’une dotation de 120 k€
  - Résultat net fiscal **augmenté** de cette dotation car déduction fiscale de l’engagement, seulement lors du paiement.

2. **Dans les comptes consolidés**

  - Vision économique sans tenir compte des décalages fiscaux, donc prise en compte de l’impact fiscal dès la constatation de la provision.
  - Constatation d’un impôt différé d’$1/4$ des $120$ k€, soit $30$ k€.

3. ** Retraitement dans les comptes consolidés**

  | IS Exigible <br> (comptes sociaux) | IS Économique <br> (comptes consolidés) 

