---
title: Analyse des performances
format:
  html: 
    toc: true
    toc-depth: 3
---

## Objectifs de cette étape

Évaluer la performance récurrente du groupe en ajustant les composantes du résultat : notion de résultat net récurrent (analyse statique des performances). Examiner les tendances de fond ou structurelles pour anticiper son évolution (analyse dynamique des performances).

## L’indicateur clés de la performance

Conserver que les produits et les charges « récurrents ». Des éléments du résultat exceptionnel peuvent avoir un caractère de récurrence (plus-values de cession, charges de restructuration…). À l’inverse, des éléments figurant en exploitation ou dans le résultat financier peuvent être non récurrents (dotation aux provisions, dépréciation de titres…).

La dotation aux amortissements (ou la reprise) des écarts d’acquisition et tout élément à caractère exceptionnel sont systématiquement écartés.
L’impôt effectif applicable au groupe est pris en compte.

> Approximation du calcul : RNR = RCAI net de la charge d’impôt (3/4 * RCAI)

### Examen des tendances

Examen du profil du groupe :

- Groupe à forte croissance = gestion des BFR ?
- Groupe opérant sur un marché mature = maîtrise des coûts ?
- Groupe en perte de vitesse = capacité d’adaptation ? 
- Analyse au regard du point mort (couverture des charges fixes), décisions prises (restructuration en cours)…
- Examen de l’origine de la variation de l’activité (analyse de l’impact de la variation du périmètre, du taux de change et de la croissance organique)
- Comparaison avec les principaux concurrents






