---
title: Indicateur Dirigeant
format: 
  html: 
    toc: true
    toc-depth: 3
---

## L’indicateur dirigeant

L’indicateur dirigeant de la Banque de France est attribué aux personnes physiques qui exercent, ou ont exercé, une fonction de dirigeant d’entreprise : 

1. soit au titre de représentant légal d’une personne morale, 
2. soit en qualité d’entrepreneur individuel ou en tant qu’associé d’une personne morale.

L’indicateur dirigeant est constitué uniquement à partir de données publiques librement accessibles auprès des greffes des tribunaux de commerce.L’indicateur dirigeant appelle l’attention des adhérents FIBEN sur des informations recueillies auprès de sources officielles. Il est dénué de tout jugement de valeur sur les capacités de gestionnaire du dirigeant.

2 valeurs possible : 

**000**

ou 

**060**

La personne physique exerce ou a exercé une fonction de représentant légal et/ou d’entrepreneur individuel dans trois entreprises au moins qui ont fait chacune l’objet d’un jugement de liquidation judiciaire datant de moins de 5 ans, sauf si ces entreprises font l’objet d’un jugement commun ou d’une extension de jugement.

La personne physique fait l’objet, à titre personnel, d’une des décision judiciaires suivantes :

- Faillite personnelle.
- Interdiction de diriger, gérer, administrer ou contrôler.
- Jugement de redressement judiciaire. (durée d’attribution : maximum 2 ans si jugement sans suite) 
- Jugement de liquidation judiciaire. (durée d’attribution : maximum 5 ans à compter de la date du jugement) 